test_file: ['data/vlue_released/vqa_vlue_test.json']
vqa_root: 'images/marvl/'
vg_root: 'images/visualgenome/'
answer_list: 'data/finetune/answer_list.json'



vision_config: 'configs/config_swinB_384.json'

use_clip_vit: False


use_swin: True
image_res: 384
patch_size: 32


use_roberta: False
text_config: 'configs/config_bert.json' 
text_encoder: 'data/bert-base-uncased'  



num_dec_layers: 6
batch_size_test: 32
max_tokens: 40
k_test: 128


