train_file: [
    "hdfs://path/to/coco",  
    "hdfs://path/to/vg",
    "hdfs://path/to/sbu",
    "hdfs://path/to/cc3m",
               ]  

train_dataset_size: 5114489 
images: {image_key: "binary",
         is_image_rpath: False, 
         caption_key: "desc",
         tokenized: False,  
         batch_size: 128,
         num_workers: 4,  
}


vision_config: 'configs/config_swinB_224.json'

use_clip_vit: False


use_swin: True
image_res: 224
patch_size: 32



use_roberta: False
text_config: 'configs/config_bert.json'  
text_encoder: 'data/bert-base-uncased' 

load_bertL_by_sep: False 


embed_dim: 256

max_words: 40
max_tokens: 40

mask_whole_word: True
mask_prob: 0.25
max_masks: 8
skipgram_prb: 0.2
skipgram_size: 3




optimizer: {opt: adamW, lr: 3e-5, weight_decay: 0.01, lr_mult: 2}
schedular: {sched: linear, lr: 3e-5, epochs: 2, num_warmup_steps: 0.1}
accelerator: {SYNCBN: false, FP16_OPT_LEVEL: O1, FP16_LOSS_SCALE: dynamic, RNG_SEED: 42, GRAD_ACCUMULATE_STEPS: 1, CLIP_GRAD_NORM: 1.0}
