train_file: ['data/finetune/refcoco+_train.json']
test_file: ['data/finetune/refcoco+_val.json','data/finetune/refcoco+_test.json']

refcoco_data: 'data/finetune/'
det_file: 'data/finetune/refcoco+/dets.json'
coco_file: 'data/finetune/refcoco+/cocos.json'

image_root: 'images/coco/'



vision_config: 'configs/config_swinB_384.json'

use_clip_vit: False


use_swin: True
image_res: 384
patch_size: 32



use_roberta: False
text_config: 'configs/config_bert.json'  
text_encoder: 'data/bert-base-uncased'  


batch_size: 20
block_num: 9
max_tokens: 40
embed_dim: 256
temp: 0.07



optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.01, lr_mult: 2}
schedular: {sched: linear, lr: 2e-5, epochs: 5, num_warmup_steps: 0.1}
