


train_file: [
    "hdfs://path/to/coco",  
    "hdfs://path/to/vg",
    "hdfs://path/to/sbu",
    "hdfs://path/to/cc3m",
    "hdfs://path/to/cc12m",
               ]  


train_dataset_size: 16219845 
images: {image_key: "binary",
         is_image_rpath: False, 
         caption_key: "caption",
         tokenized: False,  
         batch_size: 128,  
         num_workers: 4,  
}


train_file_regions: [
    'hdfs://path/to/coco_objs',
    'hdfs://path/to/vg_objs',
    'hdfs://path/to/vg_regions',
    'hdfs://path/to/openimages',
    'hdfs://path/to/obj365',
    'hdfs://path/to/refcoco_rm_leak',
]

regions: {image_key: "binary", is_image_rpath: False, caption_key: "caption", tokenized: True,
          iter_perc: 0.5, batch_size: 128, max_images: 48, max_regions: 5, min_perc_in_image: 0.5, num_workers: 2}




use_clip_vit: False



use_swin: True
vision_config: 'configs/config_swinB_224.json'
image_res: 224
patch_size: 32



use_roberta: False
text_config: 'configs/config_bert.json'  
text_encoder: 'data/bert-base-uncased'  

load_bertL_by_sep: False



calc_image_bbox_loss: False
embed_dim: 256
temp: 0.07

max_words: 30
max_tokens: 30
mask_prob: 0.25
max_masks: 6
mask_whole_word: True
skipgram_prb: 0.2
skipgram_size: 3



ckpt_frequent_step: 50000
ckpt_frequent: 5  # epoch
optimizer: {opt: adamW, lr: 1e-4, weight_decay: 0.01, lr_mult: 2}
schedular: {sched: linear, lr: 1e-4, epochs: 38, num_warmup_steps: 2500}
accelerator: {SYNCBN: false, FP16_OPT_LEVEL: O1, FP16_LOSS_SCALE: dynamic, RNG_SEED: 42, GRAD_ACCUMULATE_STEPS: 1, CLIP_GRAD_NORM: 1.0}







