train_file: ['data/finetune/vqa_train.json',
             'data/finetune/vqa_val.json',
             'data/finetune/vg_qa.json']
             
test_file: ['data/finetune/vqa_test.json']
answer_list: 'data/finetune/answer_list.json'

vqa_root: 'images/coco/'
vg_root: 'images/visualgenome/'


vision_config: 'configs/config_swinB_480.json'

use_clip_vit: False


use_swin: True
image_res: 480
patch_size: 32


use_roberta: False
text_config: 'configs/config_bert.json'  
text_encoder: 'data/bert-base-uncased' 



num_dec_layers: 6
batch_size_train: 24
batch_size_test: 32
max_tokens: 40
k_test: 128



optimizer: {opt: adamW, lr: 5e-5, weight_decay: 0.01, lr_mult: 2}
schedular: {sched: linear, lr: 5e-5, epochs: 10, num_warmup_steps: 0.1}
start_eval: 0  


